"""add loan installment adjustments

Revision ID: 0887ff610957
Revises: 910ca69c913b
Create Date: 2026-08-11 14:13:47.096873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0887ff610957'
down_revision: Union[str, None] = '910ca69c913b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_installment_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('adjusted_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'installment_number', name='uq_loan_installment_adjustment')
    )
    op.create_index(op.f('ix_loan_installment_adjustments_loan_id'), 'loan_installment_adjustments', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_installment_adjustments_loan_id'), table_name='loan_installment_adjustments')
    op.drop_table('loan_installment_adjustments')
    # ### end Alembic commands ###
