"""add transfer_reference to loan_payments

Revision ID: 3d69bf16650e
Revises: 9d0bceaf134d
Create Date: 2026-08-03 16:39:56.653044

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d69bf16650e"
down_revision: Union[str, None] = "9d0bceaf134d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loan_payments", sa.Column("transfer_reference", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loan_payments", "transfer_reference")
    # ### end Alembic commands ###
