"""add guarantee and charges to loans

Revision ID: 8e26811a6e56
Revises: 7ea55b398f13
Create Date: 2026-08-10 14:21:19.853931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e26811a6e56"
down_revision: Union[str, None] = "7ea55b398f13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loans", sa.Column("guarantee_type", sa.String(), nullable=True))
    op.add_column(
        "loans",
        sa.Column("guarantee_amount", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "loans",
        sa.Column(
            "charge_interest_tax", sa.Numeric(precision=12, scale=2), nullable=True
        ),
    )
    op.add_column(
        "loans",
        sa.Column("charge_admin_fee", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "loans",
        sa.Column(
            "charge_cancellation_insurance",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "loans",
        sa.Column(
            "charge_contracted_insurance",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loans", "charge_contracted_insurance")
    op.drop_column("loans", "charge_cancellation_insurance")
    op.drop_column("loans", "charge_admin_fee")
    op.drop_column("loans", "charge_interest_tax")
    op.drop_column("loans", "guarantee_amount")
    op.drop_column("loans", "guarantee_type")
    # ### end Alembic commands ###
