"""add extended profile fields to clients

Revision ID: 910ca69c913b
Revises: 8e26811a6e56
Create Date: 2026-08-10 15:20:15.773953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "910ca69c913b"
down_revision: Union[str, None] = "8e26811a6e56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("national_id_expiry_date", sa.Date(), nullable=True)
    )
    op.add_column("clients", sa.Column("marital_status", sa.String(), nullable=True))
    op.add_column("clients", sa.Column("education_level", sa.String(), nullable=True))
    op.add_column("clients", sa.Column("occupation", sa.String(), nullable=True))
    op.add_column("clients", sa.Column("neighborhood", sa.String(), nullable=True))
    op.add_column("clients", sa.Column("risk_rating", sa.String(), nullable=True))
    op.add_column("clients", sa.Column("economic_sector", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "economic_sector")
    op.drop_column("clients", "risk_rating")
    op.drop_column("clients", "neighborhood")
    op.drop_column("clients", "occupation")
    op.drop_column("clients", "education_level")
    op.drop_column("clients", "marital_status")
    op.drop_column("clients", "national_id_expiry_date")
    # ### end Alembic commands ###
