"""create clients, loans, loan_payments

Revision ID: 9d0bceaf134d
Revises: 9039282a0930
Create Date: 2026-07-30 16:25:28.042474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d0bceaf134d"
down_revision: Union[str, None] = "9039282a0930"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("national_id", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "declared_monthly_income", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_email"), "clients", ["email"], unique=True)
    op.create_index(
        op.f("ix_clients_national_id"), "clients", ["national_id"], unique=True
    )
    op.create_table(
        "loans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column(
            "principal_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("interest_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("term_months", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "ACTIVE",
                "PAID",
                "DEFAULTED",
                "EXPIRED",
                name="loan_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loans_client_id"), "loans", ["client_id"], unique=False)
    op.create_table(
        "loan_payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_payments_loan_id"), "loan_payments", ["loan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_loan_payments_loan_id"), table_name="loan_payments")
    op.drop_table("loan_payments")
    op.drop_index(op.f("ix_loans_client_id"), table_name="loans")
    op.drop_table("loans")
    op.drop_index(op.f("ix_clients_national_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_email"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
    sa.Enum(name="loan_status_enum").drop(op.get_bind(), checkfirst=True)
