"""add cash sessions and movements

Revision ID: b3b3955a3f99
Revises: 875e90c71fc6
Create Date: 2026-08-17 10:57:00.655132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# `payment_method_enum` se crea a mano (y se referencia con create_type=False
# más abajo) porque op.add_column NO emite el CREATE TYPE por su cuenta: solo
# op.create_table lo hace, y esta columna se agrega a una tabla que ya existe.
# Sin esto la migración falla con "type payment_method_enum does not exist".
payment_method_enum = postgresql.ENUM(
    "EFECTIVO", "TRANSFERENCIA", name="payment_method_enum"
)


# revision identifiers, used by Alembic.
revision: str = 'b3b3955a3f99'
down_revision: Union[str, None] = '875e90c71fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('cash_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cash_session_status_enum'), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opening_notes', sa.Text(), nullable=True),
    sa.Column('closing_expected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closing_counted_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closing_difference', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_notes', sa.Text(), nullable=True),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_user_id'), 'cash_sessions', ['user_id'], unique=False)
    op.create_index('uq_cash_session_open_por_usuario', 'cash_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('cash_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cash_session_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('INGRESO', 'EGRESO', name='cash_movement_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('loan_payment_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_payment_id'], ['loan_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_cash_session_id'), 'cash_movements', ['cash_session_id'], unique=False)
    op.add_column(
        'loan_payments',
        sa.Column(
            'payment_method',
            postgresql.ENUM(
                'EFECTIVO', 'TRANSFERENCIA', name='payment_method_enum',
                create_type=False,
            ),
            nullable=True,
        ),
    )
    # Nullable a propósito: los pagos anteriores a la caja son todos por
    # transferencia (era el único medio admitido), así que se leen como
    # TRANSFERENCIA desde el servicer en vez de hacer backfill.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_payments', 'payment_method')
    op.drop_index(op.f('ix_cash_movements_cash_session_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index('uq_cash_session_open_por_usuario', table_name='cash_sessions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_cash_sessions_user_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    # drop_table/drop_column no eliminan los tipos ENUM de Postgres -- sin
    # esto, volver a aplicar la migración fallaría con "type already exists".
    for nombre in (
        'payment_method_enum',
        'cash_movement_type_enum',
        'cash_session_status_enum',
    ):
        op.execute(f'DROP TYPE IF EXISTS {nombre}')
    # ### end Alembic commands ###
