"""add source_of_funds to clients

Revision ID: dafc1159158f
Revises: e5b966988ac9
Create Date: 2026-08-10 13:36:08.611999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dafc1159158f"
down_revision: Union[str, None] = "e5b966988ac9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("source_of_funds", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "source_of_funds")
    # ### end Alembic commands ###
