"""add client reference fields

Revision ID: e5b966988ac9
Revises: 3d69bf16650e
Create Date: 2026-08-04 15:51:21.756345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5b966988ac9"
down_revision: Union[str, None] = "3d69bf16650e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("personal_reference_1_name", sa.String(), nullable=True)
    )
    op.add_column(
        "clients",
        sa.Column("personal_reference_1_relationship", sa.String(), nullable=True),
    )
    op.add_column(
        "clients", sa.Column("personal_reference_1_phone", sa.String(), nullable=True)
    )
    op.add_column(
        "clients", sa.Column("personal_reference_2_name", sa.String(), nullable=True)
    )
    op.add_column(
        "clients",
        sa.Column("personal_reference_2_relationship", sa.String(), nullable=True),
    )
    op.add_column(
        "clients", sa.Column("personal_reference_2_phone", sa.String(), nullable=True)
    )
    op.add_column(
        "clients",
        sa.Column("employment_reference_employer", sa.String(), nullable=True),
    )
    op.add_column(
        "clients",
        sa.Column("employment_reference_position", sa.String(), nullable=True),
    )
    op.add_column(
        "clients", sa.Column("employment_reference_phone", sa.String(), nullable=True)
    )
    op.add_column(
        "clients",
        sa.Column("employment_reference_seniority", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "employment_reference_seniority")
    op.drop_column("clients", "employment_reference_phone")
    op.drop_column("clients", "employment_reference_position")
    op.drop_column("clients", "employment_reference_employer")
    op.drop_column("clients", "personal_reference_2_phone")
    op.drop_column("clients", "personal_reference_2_relationship")
    op.drop_column("clients", "personal_reference_2_name")
    op.drop_column("clients", "personal_reference_1_phone")
    op.drop_column("clients", "personal_reference_1_relationship")
    op.drop_column("clients", "personal_reference_1_name")
    # ### end Alembic commands ###
