# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\x04\x61uth\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"O\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x1a\n\x12\x65xpires_in_seconds\x18\x03 \x01(\x05\"%\n\rLogoutRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"!\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"D\n\x14ResetPasswordRequest\x12\x16\n\x0etarget_user_id\x18\x01 \x01(\t\x12\x14\n\x0cnew_password\x18\x02 \x01(\t\"(\n\x15ResetPasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"E\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"E\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"\x12\n\x10ListUsersRequest\"|\n\x0bUserSummary\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x11\n\tis_locked\x18\x04 \x01(\x08\x12.\n\nlast_login\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"5\n\x11ListUsersResponse\x12 \n\x05users\x18\x01 \x03(\x0b\x32\x11.auth.UserSummary2\xbd\x02\n\x0b\x41uthService\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12\x33\n\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponse\x12H\n\rResetPassword\x12\x1a.auth.ResetPasswordRequest\x1a\x1b.auth.ResetPasswordResponse\x12?\n\nCreateUser\x12\x17.auth.CreateUserRequest\x1a\x18.auth.CreateUserResponse\x12<\n\tListUsers\x12\x16.auth.ListUsersRequest\x1a\x17.auth.ListUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=61
  _globals['_LOGINREQUEST']._serialized_end=111
  _globals['_LOGINRESPONSE']._serialized_start=113
  _globals['_LOGINRESPONSE']._serialized_end=192
  _globals['_LOGOUTREQUEST']._serialized_start=194
  _globals['_LOGOUTREQUEST']._serialized_end=231
  _globals['_LOGOUTRESPONSE']._serialized_start=233
  _globals['_LOGOUTRESPONSE']._serialized_end=266
  _globals['_RESETPASSWORDREQUEST']._serialized_start=268
  _globals['_RESETPASSWORDREQUEST']._serialized_end=336
  _globals['_RESETPASSWORDRESPONSE']._serialized_start=338
  _globals['_RESETPASSWORDRESPONSE']._serialized_end=378
  _globals['_CREATEUSERREQUEST']._serialized_start=380
  _globals['_CREATEUSERREQUEST']._serialized_end=449
  _globals['_CREATEUSERRESPONSE']._serialized_start=451
  _globals['_CREATEUSERRESPONSE']._serialized_end=520
  _globals['_LISTUSERSREQUEST']._serialized_start=522
  _globals['_LISTUSERSREQUEST']._serialized_end=540
  _globals['_USERSUMMARY']._serialized_start=542
  _globals['_USERSUMMARY']._serialized_end=666
  _globals['_LISTUSERSRESPONSE']._serialized_start=668
  _globals['_LISTUSERSRESPONSE']._serialized_end=721
  _globals['_AUTHSERVICE']._serialized_start=724
  _globals['_AUTHSERVICE']._serialized_end=1041
# @@protoc_insertion_point(module_scope)
