# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cash_service_pb2 as cash__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cash_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CashServiceStub(object):
    """Módulo de caja (BR-CAJA-*): apertura de turno con efectivo inicial,
    movimientos de efectivo durante el día, y cierre con arqueo -- la
    comparación entre el efectivo que el sistema espera y el que el cajero
    contó realmente.

    Ninguna RPC recibe el id del cajero: el turno sobre el que se opera es
    siempre el del usuario autenticado (se resuelve desde el token en el
    servidor), así un cajero no puede cargar movimientos en la caja de otro.
    La única excepción es CloseCashSession, que acepta un session_id explícito
    para que un Gerente pueda cerrar una caja que quedó abierta (BR-CAJA-003).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenCashSession = channel.unary_unary(
                '/cash.CashService/OpenCashSession',
                request_serializer=cash__service__pb2.OpenCashSessionRequest.SerializeToString,
                response_deserializer=cash__service__pb2.CashSessionDetail.FromString,
                _registered_method=True)
        self.GetCurrentCashSession = channel.unary_unary(
                '/cash.CashService/GetCurrentCashSession',
                request_serializer=cash__service__pb2.GetCurrentCashSessionRequest.SerializeToString,
                response_deserializer=cash__service__pb2.GetCurrentCashSessionResponse.FromString,
                _registered_method=True)
        self.RegisterCashMovement = channel.unary_unary(
                '/cash.CashService/RegisterCashMovement',
                request_serializer=cash__service__pb2.RegisterCashMovementRequest.SerializeToString,
                response_deserializer=cash__service__pb2.CashSessionDetail.FromString,
                _registered_method=True)
        self.CloseCashSession = channel.unary_unary(
                '/cash.CashService/CloseCashSession',
                request_serializer=cash__service__pb2.CloseCashSessionRequest.SerializeToString,
                response_deserializer=cash__service__pb2.CashSessionDetail.FromString,
                _registered_method=True)
        self.ListCashSessions = channel.unary_unary(
                '/cash.CashService/ListCashSessions',
                request_serializer=cash__service__pb2.ListCashSessionsRequest.SerializeToString,
                response_deserializer=cash__service__pb2.ListCashSessionsResponse.FromString,
                _registered_method=True)


class CashServiceServicer(object):
    """Módulo de caja (BR-CAJA-*): apertura de turno con efectivo inicial,
    movimientos de efectivo durante el día, y cierre con arqueo -- la
    comparación entre el efectivo que el sistema espera y el que el cajero
    contó realmente.

    Ninguna RPC recibe el id del cajero: el turno sobre el que se opera es
    siempre el del usuario autenticado (se resuelve desde el token en el
    servidor), así un cajero no puede cargar movimientos en la caja de otro.
    La única excepción es CloseCashSession, que acepta un session_id explícito
    para que un Gerente pueda cerrar una caja que quedó abierta (BR-CAJA-003).
    """

    def OpenCashSession(self, request, context):
        """Abre el turno de caja del usuario autenticado declarando el efectivo
        inicial -- BR-CAJA-001.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentCashSession(self, request, context):
        """Turno abierto del usuario autenticado, con sus movimientos y totales.
        No es un error no tener ninguno: devuelve has_open_session = false.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCashMovement(self, request, context):
        """Registra un ingreso o egreso de efectivo en el turno abierto -- BR-CAJA-002.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseCashSession(self, request, context):
        """Cierra el turno declarando el efectivo contado; el servidor calcula el
        esperado y la diferencia -- BR-CAJA-003.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCashSessions(self, request, context):
        """Historial de arqueos. Un cajero solo ve los suyos; Gerente/Administrador
        ven los de todos los cajeros -- el filtro lo aplica el servidor según el
        rol del token, no un parámetro del request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CashServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenCashSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenCashSession,
                    request_deserializer=cash__service__pb2.OpenCashSessionRequest.FromString,
                    response_serializer=cash__service__pb2.CashSessionDetail.SerializeToString,
            ),
            'GetCurrentCashSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentCashSession,
                    request_deserializer=cash__service__pb2.GetCurrentCashSessionRequest.FromString,
                    response_serializer=cash__service__pb2.GetCurrentCashSessionResponse.SerializeToString,
            ),
            'RegisterCashMovement': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCashMovement,
                    request_deserializer=cash__service__pb2.RegisterCashMovementRequest.FromString,
                    response_serializer=cash__service__pb2.CashSessionDetail.SerializeToString,
            ),
            'CloseCashSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseCashSession,
                    request_deserializer=cash__service__pb2.CloseCashSessionRequest.FromString,
                    response_serializer=cash__service__pb2.CashSessionDetail.SerializeToString,
            ),
            'ListCashSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCashSessions,
                    request_deserializer=cash__service__pb2.ListCashSessionsRequest.FromString,
                    response_serializer=cash__service__pb2.ListCashSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cash.CashService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cash.CashService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CashService(object):
    """Módulo de caja (BR-CAJA-*): apertura de turno con efectivo inicial,
    movimientos de efectivo durante el día, y cierre con arqueo -- la
    comparación entre el efectivo que el sistema espera y el que el cajero
    contó realmente.

    Ninguna RPC recibe el id del cajero: el turno sobre el que se opera es
    siempre el del usuario autenticado (se resuelve desde el token en el
    servidor), así un cajero no puede cargar movimientos en la caja de otro.
    La única excepción es CloseCashSession, que acepta un session_id explícito
    para que un Gerente pueda cerrar una caja que quedó abierta (BR-CAJA-003).
    """

    @staticmethod
    def OpenCashSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.CashService/OpenCashSession',
            cash__service__pb2.OpenCashSessionRequest.SerializeToString,
            cash__service__pb2.CashSessionDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentCashSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.CashService/GetCurrentCashSession',
            cash__service__pb2.GetCurrentCashSessionRequest.SerializeToString,
            cash__service__pb2.GetCurrentCashSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCashMovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.CashService/RegisterCashMovement',
            cash__service__pb2.RegisterCashMovementRequest.SerializeToString,
            cash__service__pb2.CashSessionDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseCashSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.CashService/CloseCashSession',
            cash__service__pb2.CloseCashSessionRequest.SerializeToString,
            cash__service__pb2.CashSessionDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCashSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.CashService/ListCashSessions',
            cash__service__pb2.ListCashSessionsRequest.SerializeToString,
            cash__service__pb2.ListCashSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
