# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import client_service_pb2 as client__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in client_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateClient = channel.unary_unary(
                '/clients.ClientService/CreateClient',
                request_serializer=client__service__pb2.CreateClientRequest.SerializeToString,
                response_deserializer=client__service__pb2.CreateClientResponse.FromString,
                _registered_method=True)
        self.GetClientById = channel.unary_unary(
                '/clients.ClientService/GetClientById',
                request_serializer=client__service__pb2.GetClientByIdRequest.SerializeToString,
                response_deserializer=client__service__pb2.GetClientByIdResponse.FromString,
                _registered_method=True)
        self.SearchClients = channel.unary_unary(
                '/clients.ClientService/SearchClients',
                request_serializer=client__service__pb2.SearchClientsRequest.SerializeToString,
                response_deserializer=client__service__pb2.SearchClientsResponse.FromString,
                _registered_method=True)
        self.UpdateClient = channel.unary_unary(
                '/clients.ClientService/UpdateClient',
                request_serializer=client__service__pb2.UpdateClientRequest.SerializeToString,
                response_deserializer=client__service__pb2.UpdateClientResponse.FromString,
                _registered_method=True)
        self.DeactivateClient = channel.unary_unary(
                '/clients.ClientService/DeactivateClient',
                request_serializer=client__service__pb2.DeactivateClientRequest.SerializeToString,
                response_deserializer=client__service__pb2.DeactivateClientResponse.FromString,
                _registered_method=True)
        self.UpdateNationalId = channel.unary_unary(
                '/clients.ClientService/UpdateNationalId',
                request_serializer=client__service__pb2.UpdateNationalIdRequest.SerializeToString,
                response_deserializer=client__service__pb2.UpdateNationalIdResponse.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateClient(self, request, context):
        """Registro de un nuevo cliente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientById(self, request, context):
        """Obtener perfil detallado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchClients(self, request, context):
        """Búsqueda de clientes (Paginada)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClient(self, request, context):
        """Actualización de datos de contacto (y de ingresos declarados)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateClient(self, request, context):
        """Inhabilitación (soft delete) de un cliente -- BR-CLI-004 (Manager o superior)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNationalId(self, request, context):
        """Cambio del documento de identidad -- BR-CLI-003 (Solo Admin, auditado)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClient,
                    request_deserializer=client__service__pb2.CreateClientRequest.FromString,
                    response_serializer=client__service__pb2.CreateClientResponse.SerializeToString,
            ),
            'GetClientById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientById,
                    request_deserializer=client__service__pb2.GetClientByIdRequest.FromString,
                    response_serializer=client__service__pb2.GetClientByIdResponse.SerializeToString,
            ),
            'SearchClients': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchClients,
                    request_deserializer=client__service__pb2.SearchClientsRequest.FromString,
                    response_serializer=client__service__pb2.SearchClientsResponse.SerializeToString,
            ),
            'UpdateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClient,
                    request_deserializer=client__service__pb2.UpdateClientRequest.FromString,
                    response_serializer=client__service__pb2.UpdateClientResponse.SerializeToString,
            ),
            'DeactivateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateClient,
                    request_deserializer=client__service__pb2.DeactivateClientRequest.FromString,
                    response_serializer=client__service__pb2.DeactivateClientResponse.SerializeToString,
            ),
            'UpdateNationalId': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNationalId,
                    request_deserializer=client__service__pb2.UpdateNationalIdRequest.FromString,
                    response_serializer=client__service__pb2.UpdateNationalIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clients.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clients.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/CreateClient',
            client__service__pb2.CreateClientRequest.SerializeToString,
            client__service__pb2.CreateClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/GetClientById',
            client__service__pb2.GetClientByIdRequest.SerializeToString,
            client__service__pb2.GetClientByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/SearchClients',
            client__service__pb2.SearchClientsRequest.SerializeToString,
            client__service__pb2.SearchClientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/UpdateClient',
            client__service__pb2.UpdateClientRequest.SerializeToString,
            client__service__pb2.UpdateClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/DeactivateClient',
            client__service__pb2.DeactivateClientRequest.SerializeToString,
            client__service__pb2.DeactivateClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNationalId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clients.ClientService/UpdateNationalId',
            client__service__pb2.UpdateNationalIdRequest.SerializeToString,
            client__service__pb2.UpdateNationalIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
