# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dashboard_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61shboard_service.proto\x12\tdashboard\"\x1a\n\x18GetDashboardStatsRequest\"\xbf\x02\n\x19GetDashboardStatsResponse\x12\x1b\n\x13total_clients_count\x18\x01 \x01(\x05\x12\x1c\n\x14\x61\x63tive_clients_count\x18\x02 \x01(\x05\x12\x1b\n\x13pending_loans_count\x18\x03 \x01(\x05\x12\x1c\n\x14\x61pproved_loans_count\x18\x04 \x01(\x05\x12\x1a\n\x12\x61\x63tive_loans_count\x18\x05 \x01(\x05\x12\x18\n\x10paid_loans_count\x18\x06 \x01(\x05\x12\x1d\n\x15\x64\x65\x66\x61ulted_loans_count\x18\x07 \x01(\x05\x12\x1b\n\x13\x65xpired_loans_count\x18\x08 \x01(\x05\x12\x17\n\x0ftotal_disbursed\x18\t \x01(\t\x12!\n\x19total_outstanding_balance\x18\n \x01(\t2r\n\x10\x44\x61shboardService\x12^\n\x11GetDashboardStats\x12#.dashboard.GetDashboardStatsRequest\x1a$.dashboard.GetDashboardStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDASHBOARDSTATSREQUEST']._serialized_start=38
  _globals['_GETDASHBOARDSTATSREQUEST']._serialized_end=64
  _globals['_GETDASHBOARDSTATSRESPONSE']._serialized_start=67
  _globals['_GETDASHBOARDSTATSRESPONSE']._serialized_end=386
  _globals['_DASHBOARDSERVICE']._serialized_start=388
  _globals['_DASHBOARDSERVICE']._serialized_end=502
# @@protoc_insertion_point(module_scope)
