# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dashboard_service_pb2 as dashboard__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dashboard_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DashboardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDashboardStats = channel.unary_unary(
                '/dashboard.DashboardService/GetDashboardStats',
                request_serializer=dashboard__service__pb2.GetDashboardStatsRequest.SerializeToString,
                response_deserializer=dashboard__service__pb2.GetDashboardStatsResponse.FromString,
                _registered_method=True)
        self.GetPeriodReport = channel.unary_unary(
                '/dashboard.DashboardService/GetPeriodReport',
                request_serializer=dashboard__service__pb2.GetPeriodReportRequest.SerializeToString,
                response_deserializer=dashboard__service__pb2.GetPeriodReportResponse.FromString,
                _registered_method=True)


class DashboardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDashboardStats(self, request, context):
        """Estadísticas agregadas de solo lectura para la pantalla de inicio.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeriodReport(self, request, context):
        """Reporte de cierre de período (BR-DASH-002): agregados acotados a un rango
        de fechas [start_date, end_date], para presentar una vez cerrado el mes /
        trimestre / año. A diferencia de GetDashboardStats (una foto del estado
        actual), esto mide lo que *ocurrió* dentro del período.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDashboardStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardStats,
                    request_deserializer=dashboard__service__pb2.GetDashboardStatsRequest.FromString,
                    response_serializer=dashboard__service__pb2.GetDashboardStatsResponse.SerializeToString,
            ),
            'GetPeriodReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeriodReport,
                    request_deserializer=dashboard__service__pb2.GetPeriodReportRequest.FromString,
                    response_serializer=dashboard__service__pb2.GetPeriodReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dashboard.DashboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dashboard.DashboardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DashboardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDashboardStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dashboard.DashboardService/GetDashboardStats',
            dashboard__service__pb2.GetDashboardStatsRequest.SerializeToString,
            dashboard__service__pb2.GetDashboardStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeriodReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dashboard.DashboardService/GetPeriodReport',
            dashboard__service__pb2.GetPeriodReportRequest.SerializeToString,
            dashboard__service__pb2.GetPeriodReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
