# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import loan_service_pb2 as loan__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in loan_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLoan = channel.unary_unary(
                '/loans.LoanService/CreateLoan',
                request_serializer=loan__service__pb2.CreateLoanRequest.SerializeToString,
                response_deserializer=loan__service__pb2.CreateLoanResponse.FromString,
                _registered_method=True)
        self.UpdateLoanProposal = channel.unary_unary(
                '/loans.LoanService/UpdateLoanProposal',
                request_serializer=loan__service__pb2.UpdateLoanProposalRequest.SerializeToString,
                response_deserializer=loan__service__pb2.UpdateLoanProposalResponse.FromString,
                _registered_method=True)
        self.UpdateLoanGuarantee = channel.unary_unary(
                '/loans.LoanService/UpdateLoanGuarantee',
                request_serializer=loan__service__pb2.UpdateLoanGuaranteeRequest.SerializeToString,
                response_deserializer=loan__service__pb2.UpdateLoanGuaranteeResponse.FromString,
                _registered_method=True)
        self.UpdateLoanCharges = channel.unary_unary(
                '/loans.LoanService/UpdateLoanCharges',
                request_serializer=loan__service__pb2.UpdateLoanChargesRequest.SerializeToString,
                response_deserializer=loan__service__pb2.UpdateLoanChargesResponse.FromString,
                _registered_method=True)
        self.GetLoanById = channel.unary_unary(
                '/loans.LoanService/GetLoanById',
                request_serializer=loan__service__pb2.GetLoanByIdRequest.SerializeToString,
                response_deserializer=loan__service__pb2.GetLoanByIdResponse.FromString,
                _registered_method=True)
        self.ListClientLoans = channel.unary_unary(
                '/loans.LoanService/ListClientLoans',
                request_serializer=loan__service__pb2.ListClientLoansRequest.SerializeToString,
                response_deserializer=loan__service__pb2.ListClientLoansResponse.FromString,
                _registered_method=True)
        self.ListActiveLoans = channel.unary_unary(
                '/loans.LoanService/ListActiveLoans',
                request_serializer=loan__service__pb2.ListActiveLoansRequest.SerializeToString,
                response_deserializer=loan__service__pb2.ListActiveLoansResponse.FromString,
                _registered_method=True)
        self.ApproveLoan = channel.unary_unary(
                '/loans.LoanService/ApproveLoan',
                request_serializer=loan__service__pb2.ApproveLoanRequest.SerializeToString,
                response_deserializer=loan__service__pb2.ApproveLoanResponse.FromString,
                _registered_method=True)
        self.DisburseLoan = channel.unary_unary(
                '/loans.LoanService/DisburseLoan',
                request_serializer=loan__service__pb2.DisburseLoanRequest.SerializeToString,
                response_deserializer=loan__service__pb2.DisburseLoanResponse.FromString,
                _registered_method=True)
        self.RecordPayment = channel.unary_unary(
                '/loans.LoanService/RecordPayment',
                request_serializer=loan__service__pb2.RecordPaymentRequest.SerializeToString,
                response_deserializer=loan__service__pb2.RecordPaymentResponse.FromString,
                _registered_method=True)
        self.MarkDefaulted = channel.unary_unary(
                '/loans.LoanService/MarkDefaulted',
                request_serializer=loan__service__pb2.MarkDefaultedRequest.SerializeToString,
                response_deserializer=loan__service__pb2.MarkDefaultedResponse.FromString,
                _registered_method=True)
        self.GetAmortizationSchedule = channel.unary_unary(
                '/loans.LoanService/GetAmortizationSchedule',
                request_serializer=loan__service__pb2.GetAmortizationScheduleRequest.SerializeToString,
                response_deserializer=loan__service__pb2.GetAmortizationScheduleResponse.FromString,
                _registered_method=True)
        self.UpdateInstallmentAmount = channel.unary_unary(
                '/loans.LoanService/UpdateInstallmentAmount',
                request_serializer=loan__service__pb2.UpdateInstallmentAmountRequest.SerializeToString,
                response_deserializer=loan__service__pb2.UpdateInstallmentAmountResponse.FromString,
                _registered_method=True)
        self.DeleteLoan = channel.unary_unary(
                '/loans.LoanService/DeleteLoan',
                request_serializer=loan__service__pb2.DeleteLoanRequest.SerializeToString,
                response_deserializer=loan__service__pb2.DeleteLoanResponse.FromString,
                _registered_method=True)


class LoanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLoan(self, request, context):
        """Solicitud de un nuevo préstamo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLoanProposal(self, request, context):
        """Edición de la propuesta (monto, cuotas, primer vencimiento) mientras el
        préstamo esté PENDING -- BR-LOAN-004
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLoanGuarantee(self, request, context):
        """Edición de la garantía de respaldo mientras el préstamo esté PENDING -- BR-LOAN-005
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLoanCharges(self, request, context):
        """Edición de cargos/seguros mientras el préstamo esté PENDING -- BR-LOAN-006
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoanById(self, request, context):
        """Obtener el detalle de un préstamo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClientLoans(self, request, context):
        """Listar los préstamos de un cliente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveLoans(self, request, context):
        """Listar todos los préstamos ACTIVE de todos los clientes (vista
        consolidada de cartera activa, no filtrada por cliente)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveLoan(self, request, context):
        """Aprobación de un préstamo pendiente (Analista de Crédito o superior)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisburseLoan(self, request, context):
        """Desembolso de un préstamo aprobado -- Aprobado -> Activo (Gerente o superior)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordPayment(self, request, context):
        """Registro de un pago de cuota
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkDefaulted(self, request, context):
        """Marca un préstamo activo como incumplido (Analista de Crédito o superior)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAmortizationSchedule(self, request, context):
        """Plan de amortización calculado bajo demanda (no persistido)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInstallmentAmount(self, request, context):
        """Ajuste manual del monto de una cuota puntual de un préstamo ACTIVE
        (Agente de Créditos o Administrador) -- no afecta la última cuota, que
        siempre salda el remanente exacto.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLoan(self, request, context):
        """Eliminación definitiva de un préstamo cargado por error -- BR-LOAN-012.
        Solo Gerente o Administrador, y solo mientras el préstamo no haya movido
        dinero (PENDING, APPROVED o EXPIRED, y sin ningún pago registrado).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLoan,
                    request_deserializer=loan__service__pb2.CreateLoanRequest.FromString,
                    response_serializer=loan__service__pb2.CreateLoanResponse.SerializeToString,
            ),
            'UpdateLoanProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLoanProposal,
                    request_deserializer=loan__service__pb2.UpdateLoanProposalRequest.FromString,
                    response_serializer=loan__service__pb2.UpdateLoanProposalResponse.SerializeToString,
            ),
            'UpdateLoanGuarantee': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLoanGuarantee,
                    request_deserializer=loan__service__pb2.UpdateLoanGuaranteeRequest.FromString,
                    response_serializer=loan__service__pb2.UpdateLoanGuaranteeResponse.SerializeToString,
            ),
            'UpdateLoanCharges': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLoanCharges,
                    request_deserializer=loan__service__pb2.UpdateLoanChargesRequest.FromString,
                    response_serializer=loan__service__pb2.UpdateLoanChargesResponse.SerializeToString,
            ),
            'GetLoanById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoanById,
                    request_deserializer=loan__service__pb2.GetLoanByIdRequest.FromString,
                    response_serializer=loan__service__pb2.GetLoanByIdResponse.SerializeToString,
            ),
            'ListClientLoans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClientLoans,
                    request_deserializer=loan__service__pb2.ListClientLoansRequest.FromString,
                    response_serializer=loan__service__pb2.ListClientLoansResponse.SerializeToString,
            ),
            'ListActiveLoans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveLoans,
                    request_deserializer=loan__service__pb2.ListActiveLoansRequest.FromString,
                    response_serializer=loan__service__pb2.ListActiveLoansResponse.SerializeToString,
            ),
            'ApproveLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveLoan,
                    request_deserializer=loan__service__pb2.ApproveLoanRequest.FromString,
                    response_serializer=loan__service__pb2.ApproveLoanResponse.SerializeToString,
            ),
            'DisburseLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.DisburseLoan,
                    request_deserializer=loan__service__pb2.DisburseLoanRequest.FromString,
                    response_serializer=loan__service__pb2.DisburseLoanResponse.SerializeToString,
            ),
            'RecordPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordPayment,
                    request_deserializer=loan__service__pb2.RecordPaymentRequest.FromString,
                    response_serializer=loan__service__pb2.RecordPaymentResponse.SerializeToString,
            ),
            'MarkDefaulted': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkDefaulted,
                    request_deserializer=loan__service__pb2.MarkDefaultedRequest.FromString,
                    response_serializer=loan__service__pb2.MarkDefaultedResponse.SerializeToString,
            ),
            'GetAmortizationSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAmortizationSchedule,
                    request_deserializer=loan__service__pb2.GetAmortizationScheduleRequest.FromString,
                    response_serializer=loan__service__pb2.GetAmortizationScheduleResponse.SerializeToString,
            ),
            'UpdateInstallmentAmount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInstallmentAmount,
                    request_deserializer=loan__service__pb2.UpdateInstallmentAmountRequest.FromString,
                    response_serializer=loan__service__pb2.UpdateInstallmentAmountResponse.SerializeToString,
            ),
            'DeleteLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLoan,
                    request_deserializer=loan__service__pb2.DeleteLoanRequest.FromString,
                    response_serializer=loan__service__pb2.DeleteLoanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loans.LoanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loans.LoanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/CreateLoan',
            loan__service__pb2.CreateLoanRequest.SerializeToString,
            loan__service__pb2.CreateLoanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLoanProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/UpdateLoanProposal',
            loan__service__pb2.UpdateLoanProposalRequest.SerializeToString,
            loan__service__pb2.UpdateLoanProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLoanGuarantee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/UpdateLoanGuarantee',
            loan__service__pb2.UpdateLoanGuaranteeRequest.SerializeToString,
            loan__service__pb2.UpdateLoanGuaranteeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLoanCharges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/UpdateLoanCharges',
            loan__service__pb2.UpdateLoanChargesRequest.SerializeToString,
            loan__service__pb2.UpdateLoanChargesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoanById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/GetLoanById',
            loan__service__pb2.GetLoanByIdRequest.SerializeToString,
            loan__service__pb2.GetLoanByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClientLoans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/ListClientLoans',
            loan__service__pb2.ListClientLoansRequest.SerializeToString,
            loan__service__pb2.ListClientLoansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveLoans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/ListActiveLoans',
            loan__service__pb2.ListActiveLoansRequest.SerializeToString,
            loan__service__pb2.ListActiveLoansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/ApproveLoan',
            loan__service__pb2.ApproveLoanRequest.SerializeToString,
            loan__service__pb2.ApproveLoanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisburseLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/DisburseLoan',
            loan__service__pb2.DisburseLoanRequest.SerializeToString,
            loan__service__pb2.DisburseLoanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/RecordPayment',
            loan__service__pb2.RecordPaymentRequest.SerializeToString,
            loan__service__pb2.RecordPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkDefaulted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/MarkDefaulted',
            loan__service__pb2.MarkDefaultedRequest.SerializeToString,
            loan__service__pb2.MarkDefaultedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAmortizationSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/GetAmortizationSchedule',
            loan__service__pb2.GetAmortizationScheduleRequest.SerializeToString,
            loan__service__pb2.GetAmortizationScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInstallmentAmount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/UpdateInstallmentAmount',
            loan__service__pb2.UpdateInstallmentAmountRequest.SerializeToString,
            loan__service__pb2.UpdateInstallmentAmountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loans.LoanService/DeleteLoan',
            loan__service__pb2.DeleteLoanRequest.SerializeToString,
            loan__service__pb2.DeleteLoanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
